development: &default
  adapter: postgresql
  database: good_things_dev
  username: postgres
  host: localhost
  encoding: utf8
  reconnect: true

test:
  <<: *default
  database: good_things_test

staging:
  <<: *default
  database: good_things_staging

production:
  <<: *default
  adapter: postgresql
  database: good_things_dev
